export type ServiceData = {
  slug: string
  icon: string
  cat: string
  name: string
  summary: string
  desc: string
  tags: string[]
  highlights: { title: string; desc: string }[]
  specs: string[]
  useCases: string[]
  cta: string
}

export const servicesData: ServiceData[] = [
  {
    slug: 'server-rental',
    icon: '🏢',
    cat: 'IDC / 서버',
    name: '서버 임대 · 코로케이션',
    summary: '전용서버·VPS·고객 장비 입주. 전력·냉각·네트워크 포함.',
    desc: '가상화 기반 VM 즉시 할당부터 고객 장비 입주(코로케이션)까지, 유연한 형태로 서버 인프라를 구성할 수 있습니다. 전력·냉각·네트워크 회선이 포함되며, IPMI를 통한 원격 콘솔 접근이 가능합니다.',
    tags: ['KVM', 'IPMI', 'Bare Metal', 'VPS', '코로케이션'],
    highlights: [
      { title: '즉시 할당 VM', desc: 'KVM 기반 가상서버 최소 1시간 이내 할당. 사양 유연 조정 가능.' },
      { title: '베어메탈 전용서버', desc: '고성능 단독 서버 임대. 타 고객 자원 공유 없는 완전 독립 환경.' },
      { title: '코로케이션', desc: '고객 보유 장비를 IDC에 입주. 전력·냉각·네트워크 제공.' },
      { title: 'IPMI 원격관리', desc: '장애 시 원격 콘솔 및 전원 제어. 현장 방문 없이 복구 가능.' },
    ],
    specs: [
      '가상서버(VPS): vCPU 2~64코어, RAM 2GB~256GB, NVMe SSD',
      '베어메탈: E5/Xeon 시리즈, 최대 512GB RAM',
      '네트워크: 1Gbps ~ 10Gbps 업링크, 트래픽 기본 포함',
      '전원: 이중화 PDU, UPS 상시 대기',
      '보안: 물리적 출입 통제, CCTV 24시간 녹화',
      '원격 접근: IPMI/iDRAC, VPN 전용 채널',
    ],
    useCases: [
      '게임 서버 / 채팅 서버 운영',
      '기업 내부 시스템 이전',
      '웹·앱 서비스 인프라 구축',
      '개발·스테이징 환경 분리',
      '데이터 분석 / GPU 연산 서버',
    ],
    cta: '서버 임대 상담 신청',
  },
  {
    slug: 'managed-service',
    icon: '⚙️',
    cat: 'IDC / MSP',
    name: '위탁운영 매니지먼트',
    summary: 'OS 패치·장애대응·성능튜닝 전담. 실시간 모니터링 + 월 SLA 리포트.',
    desc: '서버 운영의 모든 것을 전문 엔지니어에게 맡기세요. OS 보안 패치, 장애 대응, 성능 튜닝부터 정기 리포트까지 완전 위탁 운영 서비스를 제공합니다.',
    tags: ['Zabbix', 'Ansible', 'Grafana', 'Nagios', 'Shell'],
    highlights: [
      { title: 'OS 패치 & 보안 업데이트', desc: 'Linux/Windows 보안 취약점 패치 정기 적용. CVE 모니터링 포함.' },
      { title: '24시간 장애 대응', desc: '이상 감지 시 즉시 알림 + 엔지니어 대응. 4시간 이내 복구 SLA.' },
      { title: 'Zabbix 실시간 모니터링', desc: 'CPU·메모리·디스크·네트워크 수치 실시간 수집. 임계값 초과 시 자동 알림.' },
      { title: '월간 SLA 리포트', desc: '가용성·장애 내역·성능 트렌드 월 1회 리포트 제공.' },
    ],
    specs: [
      '모니터링: Zabbix + Grafana 대시보드 제공',
      '패치 주기: 긴급 패치 24시간 이내, 정기 패치 월 1회',
      '장애 대응 SLA: 4시간 이내 복구',
      '자동화: Ansible 기반 반복 작업 자동화',
      '알림: 이메일·Slack·SMS 선택 가능',
      '리포트: 월간 PDF 리포트 이메일 발송',
    ],
    useCases: [
      'IT 인력이 없는 중소기업',
      '서버 운영 비용 절감이 필요한 기업',
      '24시간 가용성이 필요한 서비스',
      '보안 컴플라이언스 준수 필요',
      '다수 서버 일괄 관리',
    ],
    cta: '위탁운영 상담 신청',
  },
  {
    slug: 'ha',
    icon: '🔄',
    cat: 'IDC / HA',
    name: '운영서버 이중화 (HA)',
    summary: 'Active-Active/Standby 구성. 자동 페일오버 30초 이내, 99.99% SLA.',
    desc: '서버 장애 시 서비스 중단을 최소화하는 고가용성(HA) 구성을 제공합니다. Active-Active 또는 Active-Standby 방식으로 설계하며, 자동 페일오버로 30초 이내 전환을 보장합니다.',
    tags: ['Keepalived', 'HAProxy', 'Pacemaker', 'DRBD', 'Corosync'],
    highlights: [
      { title: 'Active-Active 구성', desc: '두 서버가 동시에 트래픽 처리. 부하 분산 + 장애 대응 동시 구현.' },
      { title: '자동 페일오버 30초', desc: '주 서버 장애 감지 시 30초 이내 자동으로 보조 서버로 전환.' },
      { title: 'L4/L7 로드밸런서', desc: 'HAProxy 기반 트래픽 분산. 헬스체크로 비정상 서버 자동 제외.' },
      { title: 'VIP (가상 IP) 관리', desc: 'Keepalived로 가상 IP 유지. 클라이언트 변경 없이 투명한 전환.' },
    ],
    specs: [
      '구성 방식: Active-Active / Active-Standby 선택',
      '페일오버 시간: 30초 이내 자동 전환',
      'SLA: 99.99% 가용성 보장',
      '로드밸런서: HAProxy L4/L7',
      'HA 클러스터: Pacemaker + Corosync',
      '스토리지 동기화: DRBD 실시간 블록 복제',
    ],
    useCases: [
      '무중단 서비스가 필요한 쇼핑몰',
      '금융·결제 시스템',
      '실시간 게임 서버',
      '기업 핵심 업무 시스템',
      '의료·공공 서비스 인프라',
    ],
    cta: 'HA 구성 상담 신청',
  },
  {
    slug: 'db-cluster',
    icon: '🗄️',
    cat: 'IDC / DB',
    name: 'DB 이중화 매니지먼트',
    summary: 'Galera Cluster·Master-Slave 구성·모니터링·자동복구 위탁관리.',
    desc: '데이터베이스 이중화 설계부터 일상 운영까지 전담합니다. Galera Cluster 또는 Master-Slave 구성으로 데이터 유실을 방지하고, 슬로우 쿼리 분석으로 성능을 지속 최적화합니다.',
    tags: ['Galera', 'ProxySQL', 'Percona', 'MariaDB', 'MySQL'],
    highlights: [
      { title: 'Galera Cluster', desc: 'Multi-Master 동기 복제. 어느 노드에서나 쓰기 가능, 자동 동기화.' },
      { title: 'ProxySQL 로드밸런싱', desc: 'DB 앞단에서 읽기/쓰기 분리. 장애 노드 자동 제외 및 재연결.' },
      { title: '슬로우 쿼리 분석', desc: '성능 저하 쿼리 자동 감지 및 최적화 권고. 정기 분석 리포트 제공.' },
      { title: '자동 복구', desc: '노드 장애 시 클러스터 자동 재합류. 데이터 정합성 자동 검증.' },
    ],
    specs: [
      'DB 엔진: MariaDB / MySQL / Percona',
      '클러스터: Galera Multi-Master (3노드 이상 권장)',
      '복제: Master-Slave 비동기 / GTID 동기',
      '프록시: ProxySQL 읽기/쓰기 분리',
      '백업: Xtrabackup 물리 백업 일 1회',
      '모니터링: 쿼리 응답시간·슬로우쿼리·복제 지연 감시',
    ],
    useCases: [
      '대용량 트래픽 쇼핑몰 DB',
      '실시간 데이터 처리 서비스',
      '멀티 리전 서비스 데이터 동기화',
      'ERP / CRM 시스템 DB',
      '게임 캐릭터 데이터 보호',
    ],
    cta: 'DB 이중화 상담 신청',
  },
  {
    slug: 'ai-stream-security',
    icon: '🛡️',
    cat: 'AI 보안',
    name: 'AI 스트림 이상탐지',
    summary: 'RTMP/HLS 트래픽 머신러닝 분석. DDoS·세션 하이재킹 실시간 자동차단.',
    desc: '스트리밍 인프라를 겨냥한 사이버 공격을 AI가 실시간으로 탐지하고 자동 차단합니다. RTMP/HLS 트래픽 패턴을 머신러닝으로 분석해 기존 룰 기반 보안이 놓치는 이상 행위를 검출합니다.',
    tags: ['Python ML', 'MediaMTX', 'Fail2ban', 'eBPF', 'XDP'],
    highlights: [
      { title: 'RTMP/HLS 트래픽 분석', desc: '스트리밍 프로토콜 레벨에서 패킷 분석. 비정상 세션 패턴 즉시 탐지.' },
      { title: 'DDoS 자동 차단', desc: '초당 요청 수 급증 시 IP 자동 차단. XDP/eBPF 커널 레벨 필터링.' },
      { title: '세션 하이재킹 탐지', desc: '스트림 키 도용·무단 재송출 행위 감지 및 즉시 세션 종료.' },
      { title: '인젝션 공격 방어', desc: 'HLS 메타데이터·RTMP AMF 인젝션 시도 탐지 및 차단.' },
    ],
    specs: [
      '분석 대상: RTMP, HLS, WebRTC, SRT, RTSP',
      '탐지 방식: 머신러닝 이상탐지 + 룰 기반 하이브리드',
      '자동 대응: IP 차단, 세션 강제 종료, 알림 발송',
      '응답 시간: 이상 감지 후 5초 이내 차단',
      '로그: 전체 이벤트 로그 90일 보관',
      '대시보드: 실시간 트래픽 시각화 제공',
    ],
    useCases: [
      '라이브 스트리밍 플랫폼 보안',
      'OTT 서비스 불법 유출 방지',
      '기업 화상회의 인프라 보호',
      '스포츠 중계 무단 재송출 차단',
      '방송사 스트리밍 인프라 보안',
    ],
    cta: 'AI 보안 상담 신청',
  },
  {
    slug: 'deepfake-detection',
    icon: '🔍',
    cat: 'AI 보안',
    name: '딥페이크 탐지 서비스',
    summary: '라이브 스트림 내 AI 합성 영상·음성 실시간 검출. 방송사·기업 미디어 대상.',
    desc: '실시간 라이브 스트림에서 딥페이크 합성 영상과 AI 생성 음성을 자동으로 검출합니다. 방송 사고, 허위 정보 유포, 사기 피해를 사전에 방지합니다.',
    tags: ['PyTorch', 'ONNX', 'FaceForensics', 'DeepFaceLab', 'TensorRT'],
    highlights: [
      { title: '실시간 영상 분석', desc: '라이브 스트림 프레임을 실시간 분석. 딥페이크 탐지 정확도 95% 이상.' },
      { title: 'AI 음성 합성 탐지', desc: 'TTS·보이스 클로닝으로 생성된 합성 음성 식별. 보이스피싱 대응.' },
      { title: '자동 알림 & 차단', desc: '딥페이크 감지 시 즉시 운영자 알림 + 선택적 스트림 차단.' },
      { title: '다중 모델 앙상블', desc: 'FaceForensics++ 학습 모델 + 자체 파인튜닝. 오탐지율 최소화.' },
    ],
    specs: [
      '분석 방식: 프레임 단위 CNN + 시계열 LSTM 분석',
      '지원 포맷: RTMP, HLS, MP4, WebRTC',
      '탐지 정확도: 95% 이상 (실제 딥페이크 영상 기준)',
      '처리 속도: 1080p 기준 실시간 처리 (GPU 가속)',
      '음성 탐지: GAN 생성 음성, TTS, 보이스 클로닝',
      '리포트: 탐지 이벤트 스크린샷 + 타임스탬프 기록',
    ],
    useCases: [
      '뉴스·방송사 실시간 스트리밍 감시',
      '기업 임원 화상 회의 보안',
      '금융 비대면 본인인증 위변조 탐지',
      '온라인 교육 플랫폼 신뢰성 확보',
      '선거·정치 콘텐츠 조작 탐지',
    ],
    cta: '딥페이크 탐지 상담 신청',
  },
  {
    slug: 'ultrastream',
    icon: '📡',
    cat: '스트리밍',
    name: 'Ultrastream 엔진 호스팅',
    summary: 'MediaMTX 기반 RTMP/HLS/WebRTC. LL-HLS 1~2초 레이턴시, ABR 4단계.',
    desc: 'LunarFlux의 자체 스트리밍 엔진 Ultrastream으로 초저지연 라이브 방송 인프라를 구축하세요. RTMP 수신부터 HLS 변환, WebRTC 배포까지 하나의 파이프라인으로 처리합니다.',
    tags: ['MediaMTX', 'FFmpeg', 'WebRTC', 'LL-HLS', 'SRT'],
    highlights: [
      { title: 'LL-HLS 초저지연', desc: '1~2초 레이턴시 라이브 스트리밍. 기존 HLS(10~30초) 대비 10배 빠름.' },
      { title: 'ABR 4단계 적응형', desc: '1080p/720p/480p/360p 자동 화질 전환. 시청자 네트워크 환경 최적화.' },
      { title: '멀티 프로토콜 지원', desc: 'RTMP·HLS·WebRTC·SRT·RTSP 동시 지원. OBS/인코더 즉시 연동.' },
      { title: '무제한 동시 시청', desc: 'CDN 연동으로 동시 시청자 수 제한 없이 확장. 대규모 이벤트 대응.' },
    ],
    specs: [
      '수신 프로토콜: RTMP, SRT, RTSP',
      '배포 프로토콜: HLS, LL-HLS, WebRTC, DASH',
      '인코딩: FFmpeg ABR 4단계 (1080p~360p)',
      '레이턴시: LL-HLS 1~2초, WebRTC 0.5초 이하',
      '동시 채널: 플랜에 따라 1~무제한',
      '부가 기능: 스트림 키 관리, 자동 재연결, 녹화',
    ],
    useCases: [
      '이커머스 라이브 쇼핑 방송',
      '온라인 콘서트·공연 중계',
      '스포츠 경기 실시간 중계',
      '기업 내부 방송·타운홀',
      '온라인 교육 강의 스트리밍',
    ],
    cta: '스트리밍 상담 신청',
  },
  {
    slug: 'vod-multistream',
    icon: '🎬',
    cat: '스트리밍',
    name: 'VOD 관리 + 멀티 리스트림',
    summary: 'VOD 저장·썸네일 자동생성. 유튜브·트위치·네이버 동시 송출 자동화.',
    desc: '라이브 방송을 자동으로 녹화·저장하고 VOD로 관리합니다. 동시에 유튜브·트위치·네이버TV 등 여러 플랫폼에 자동 동시 송출하여 최대 노출 효과를 얻으세요.',
    tags: ['MariaDB', 'Cloudflare', 'FFmpeg', 'YouTube API', 'Twitch'],
    highlights: [
      { title: 'VOD 자동 저장', desc: '라이브 방송 종료 시 자동 녹화본 저장. 고화질 MP4 + 세그먼트 보관.' },
      { title: '썸네일 자동생성', desc: 'FFmpeg으로 구간별 썸네일 자동 추출. 수동 작업 불필요.' },
      { title: '멀티플랫폼 동시 송출', desc: '유튜브·트위치·네이버TV·아프리카TV 동시 스트리밍. 키 관리 자동화.' },
      { title: 'CDN 배포', desc: 'Cloudflare Stream 연동으로 전 세계 빠른 VOD 재생. 트래픽 과금 최소화.' },
    ],
    specs: [
      'VOD 저장: MP4 H.264/H.265, 최대 4K',
      '썸네일: 방송 구간별 자동 추출, JPG/WebP',
      '동시 송출: 최대 10개 플랫폼 동시 재스트림',
      '지원 플랫폼: YouTube, Twitch, Naver, AfreecaTV, Facebook',
      'CDN: Cloudflare 연동, 글로벌 배포',
      '저장 용량: 플랜에 따라 50GB~무제한',
    ],
    useCases: [
      '유튜브·트위치 동시 방송 크리에이터',
      '쇼핑몰 라이브 커머스 아카이빙',
      '방송사 다중 채널 동시 배포',
      '교육 콘텐츠 다플랫폼 배포',
      '기업 웨비나 녹화·배포',
    ],
    cta: 'VOD / 리스트림 상담 신청',
  },
  {
    slug: 'ai-agent',
    icon: '🤖',
    cat: 'AI 보안',
    name: 'AI 자율 관제 에이전트',
    summary: 'LLM 기반 SOC 에이전트. 위협탐지→분석→대응 자동화로 24/7 무인 관제.',
    desc: 'LLM(대규모 언어 모델)을 활용한 차세대 SOC 자동화 에이전트입니다. 보안 이벤트를 스스로 분석하고, 대응 방안을 결정하며, 실행까지 자동화합니다. 24시간 무인 관제를 실현합니다.',
    tags: ['Claude API', 'Wazuh', 'SOAR', 'SIEM', 'LangChain'],
    highlights: [
      { title: 'LLM 기반 위협 분석', desc: 'Claude API로 보안 이벤트 자연어 분석. 맥락을 이해하는 지능형 대응.' },
      { title: 'SOAR 자동화', desc: '위협 탐지 → 분석 → 격리 → 보고까지 전 과정 자동화. 사람 개입 최소화.' },
      { title: 'Wazuh SIEM 연동', desc: '통합 보안 이벤트 수집·분석. 수천 개 규칙 기반 + AI 이상탐지 하이브리드.' },
      { title: '24/7 무인 관제', desc: '야간·주말 포함 연중무휴 자동 관제. 중요 이벤트만 담당자에게 에스컬레이션.' },
    ],
    specs: [
      'AI 엔진: Claude API + 자체 파인튜닝 모델',
      'SIEM: Wazuh 기반 로그 수집·분석',
      '자동화: SOAR 플레이북 50+ 시나리오',
      '커버리지: 서버·네트워크·앱·클라우드 통합 관제',
      '에스컬레이션: 임계 위협 시 즉시 담당자 알림',
      '리포트: 일간·주간·월간 보안 현황 리포트',
    ],
    useCases: [
      '보안 인력이 부족한 중견기업',
      '24시간 관제가 필요한 금융·의료',
      '클라우드 인프라 보안 자동화',
      '컴플라이언스 감사 로그 자동화',
      '멀티 클라우드 통합 보안 관제',
    ],
    cta: 'AI 관제 에이전트 상담 신청',
  },
]

export function getServiceBySlug(slug: string): ServiceData | undefined {
  return servicesData.find(s => s.slug === slug)
}
